### ISSUE TITLE
Ports missing if Folding is first module selected

### ISSUE THREAD

**Issue by SteveRussell33** [AnimatedCircuits/RackModules#1]
![folding](https://user-images.githubusercontent.com/41975381/60993106-b66a4700-a345-11e9-8ef9-aff9fe3df3e8.png)
Duplicating with Ctrl+D or from module browser displays module with ports intact.

If Folding is added to a non-empty Rack then all ports are shown.
![folding2](https://user-images.githubusercontent.com/41975381/60994458-7a84b100-a348-11e9-9c18-dd94b7f52e51.png)

BTW the Preview models exhibt this behaviour as well.

**Comment by AnimatedCircuits** [comment]
Can you reproduce it with the official release (not dev) version of Rack ? I can't. Thank you

**Comment by SteveRussell33** [comment]
Same here; closing
