### ISSUE TITLE
Runtime dark mode and derivative work

### ISSUE THREAD

**Issue by falkTX** [AnimatedCircuits/RackModules#7]
Hi there.

I have a question regarding using your modules and applying a special dark mode at runtime.
It is unclear to me if this constitutes derivative work, since no files are ever changed and no new work is written on disk.

But might as well ask anyway.
The panels look like this:

![Screenshot_20220213_221136](https://user-images.githubusercontent.com/1334853/153777436-4a702737-6f99-441e-b717-08528c997b05.png)

Are you ok with this or should I remove the logo and rename the project?

**Comment by falkTX** [comment]
If you actually like this look, I can create a PR to add a dark mode switch.
The code to do this is quite simple, it basically goes through the paths generated by nanosvg and inverts very specific colors. As you can see in the pic, the blue still remains blue. it is not a pure inversion.

**Comment by AnimatedCircuits** [comment]
Hi !

All good ! It’s ok for me. You can create the PR too.
Sebastien

**Comment by falkTX** [comment]
This is now handled in #8 thanks!
